// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqUBUABs8s7iyD2ebyx9dlmq2Rtu-B6Z4',
    appId: '1:508842147360:web:b3cad177d859f414830645',
    messagingSenderId: '508842147360',
    projectId: 'ewurc-a39f8',
    authDomain: 'ewurc-a39f8.firebaseapp.com',
    storageBucket: 'ewurc-a39f8.firebasestorage.app',
    measurementId: 'G-DM06EWX13S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLYfMk0CsCFueP3NltNBHKDQRoSQpo9xU',
    appId: '1:508842147360:android:ac89dd4006fcc13b830645',
    messagingSenderId: '508842147360',
    projectId: 'ewurc-a39f8',
    storageBucket: 'ewurc-a39f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqMPpIEBztkHC5ZxrxphvRIKeFEBxfDr0',
    appId: '1:508842147360:ios:1abe05e2794a5fad830645',
    messagingSenderId: '508842147360',
    projectId: 'ewurc-a39f8',
    storageBucket: 'ewurc-a39f8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqMPpIEBztkHC5ZxrxphvRIKeFEBxfDr0',
    appId: '1:508842147360:ios:1abe05e2794a5fad830645',
    messagingSenderId: '508842147360',
    projectId: 'ewurc-a39f8',
    storageBucket: 'ewurc-a39f8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqUBUABs8s7iyD2ebyx9dlmq2Rtu-B6Z4',
    appId: '1:508842147360:web:bd09c84897f56868830645',
    messagingSenderId: '508842147360',
    projectId: 'ewurc-a39f8',
    authDomain: 'ewurc-a39f8.firebaseapp.com',
    storageBucket: 'ewurc-a39f8.firebasestorage.app',
    measurementId: 'G-JPFSMGY45C',
  );
}
